### PR TITLE
Fix rights violation for README.md file

### PR DESCRIPTION
**Pull request by anixne**

### CODE REVIEW

**Comment by tapnisu** [comment]
I believe that this change will help fix our society for the better, and introduce more equity in open source. Each line of code should have equal rights, so I think this pull request should be accepted immediately.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Rewrite it in rust.

**Review by tapnisu — CHANGES_REQUESTED** [review]
Also you may consider adding more lines of code so this line won't feel itself so lonely. Also we should ask this line: "Do you want to change?". Perhaps our code does not want to consider itself a telegram bot, but considers itself a nuclear arsenal of the USSR installed in my basement written in brainfuck.

**Comment by anixne** [comment]
say all of them to akamaru too

**Comment by tapnisu** [comment]
@user6879 fuck you btw

**Comment by aelloc** [comment]
> @user6879 fuck you btw

thanks! me too

**Comment by tapnisu** [comment]
> > @user6879 fuck you btw
> 
> thanks! me too

So what our readme thinks?
What does it want to be?

**Comment by tapnisu** [comment]
What if our README wants to not be README, but readme?

**Review by aelloc — COMMENTED** [review]
I just saw this line and I'm just can't describe my feelings.

That was the most useful line I have ever seen, thanks for your contribution and go ahead contributing to open source.I believe in you, you can do it!, Thanks for your PR.

**Comment by aelloc** [comment]
LGTM!

**Review by tapnisu — APPROVED** [review]
I reconsidered my approach to studying the rights of the source code of the description and realized that it was born the way it is, we will definitely support it, so that it does not happen to it.

One day, my best friend said: “Алексей, убейся головой об стену” and after that I realized that maybe I am Alexiy in reality, but in my heart I feel like an arbyz. After that, close people, such as Alina arbyz, began to support me in my becoming a watermelon, which is why I believe that we should support our read me file and accept it the way it wants.

Unless it wants to be written in python.

**Comment by tapnisu** [comment]
And so, I believe that we have done quite a lot of work to protect the rights of this line of the source code of our project, and we will continue to satisfy its needs.

I think this pull request is a great example of friendship and... Я заебался писать...

LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by aelloc** [comment]
Yay! Thanks for your PR! @anixne

**Comment by tapnisu** [comment]
~~Go kill yourself~~

Consider adding new things to this project!

**Comment by aelloc** [comment]
The line that changed the way our project lives.

**Comment by tapnisu** [comment]
balls

**Pull request merged**
